module.exports = {
  PING_EVENT: "SWARM_QUEEN_PING_EVENT",
  LOG_EVENT: "SWARM_QUEEN_LOG_EVENT",
  BOOTSTRAP_SWARM_RPC: "SWARM_QUEEN_BOOTSTRAP_SWARM_RPC",
  GET_JOIN_ADDR_RPC: "SWARM_QUEEN_GET_JOIN_ADDR_RPC",
  DOCKER_COMMAND_RPC: "SWARM_QUEEN_DOCKER_COMMAND_RPC",
}
